## Tensors

In [1]:
import torch
import numpy as np

In [2]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 1.8601,  0.6167, -2.7251, -0.0531],
        [-0.7585, -1.0582, -1.2866, -0.1075],
        [-0.6484, -0.0409, -0.3804, -0.0174]])

In [3]:
t1 = torch.arange(12)
t1

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
t1.view(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [5]:
t1.view(2,3,2)

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])

In [9]:
t1.view(3,2,-1)

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])